<Project>
  <ItemGroup>
    <PackageVersion Include="eQuantic.Mapper" Version="2.2.1" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup Label="Tests">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
  </ItemGroup>
</Project>
